version: "3.9"

services:
    db:
        container_name: movies-db
        image: postgres:14.1
        restart: always
        environment:
            POSTGRES_DB: movies
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 12345
        networks:
            - movies-network
        ports:
            - "5432:5432"
